# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
sample_pois <- function(n, theta, gam, burn_in = 1000L, spacing = 100L, verb = TRUE) {
    .Call(`_pois_sample_pois`, n, theta, gam, burn_in, spacing, verb)
}

